### ISSUE TITLE
Inclusion du saut de vecteur adjoint dans la méthode directe 

### ISSUE THREAD

**Issue by AnasXbouali** [control-toolbox/control-loss#2]
@ocots ; Le premier exemple de Zermelo, qui ne comporte qu'une seule région de perte de contrôle, nécessite normalement l'introduction du saut du vecteur adjoint dans la méthode directe. J'ai tenté de l'intégrer, mais je rencontre un problème de dépassement de la longueur des vecteurs.

    px10 =   dual(con_x10)
    px20 =   dual(con_x20)
    px2f = - dual(con_x2f)  

    # Costate jump
    jump_index1 = -1
    jump_index2 = -1

    jump1 = 0.0
    jump2 = 0.0

    # locate jump1
    for i in 1:size(x2)[1]
        if x2[i] > 0.5
            jump_index1 = i 
            break
        end
    end

    # locate jump2
    for i in 1:size(x2)[1] 
        if x2[i] > 3.5 
            jump_index2 = i 
            break
        end
    end

    # keep original signs for now
    sign = 1
    
     px11 = [ dual(con_dx1[i]) for i in 1:jump_index1 ]
     px21 = [ dual(con_dx2[i]) for i in 1:jump_index1 ]

     px11 = sign * [px10; (px11[1:jump_index1-1]+px11[2:jump_index1])/2.];
     px21 = sign * [px20; (px21[1:jump_index1-1]+px21[2:jump_index1])/2.]; 
    
     p11  = - [px10; px11[1:jump_index1] ];
     p21  = - [px20; px21[1:jump_index1] ];
    
     jump1  = p21[jump_index1]*( - u[jump_index1] + a)/x2[jump_index1]     # jump vector at t=t1
    
     px12 = [ dual(con_dx1[i]) for i in jump_index1+1:jump_index2 ]
     px22 = [ dual(con_dx2[i]) for i in jump_index1+1:jump_index2 ]

     px12 = sign * [p11[jump_index1] - jump1 ; (px12[jump_index1:jump_index2-1]+px1[jump_index1+1:jump_index2])/2.];
     px22 = sign * [p21[jump_index1]         ; (px22[jump_index1:jump_index2-1]+px2[jump_index1+1:jump_index2])/2.]; 
    
     p12  = - [p11[jump_index1] - jump1; px12[jump_index1:jump_index2] ];
     p22  = - [p21[jump_index1]        ; px22[jump_index1:jump_index2] ];
    
     jump2  = p22[jump_index2]*(  u[jump_index2] - a)/x2[jump_index2];    # jump vector at t=t2
    
     px13 = [ dual(con_dx1[i]) for i in jump_index2+1:N ]
     px23 = [ dual(con_dx2[i]) for i in jump_index2+1:N ]

     px13 = sign * [p12[jump_index2] - jump2 ; (px13[jump_index2:N-1]+px3[jump_index2+1:N])/2.];
     px23 = sign * [p22[jump_index2]         ; (px23[jump_index2:N-1]+px3[jump_index2+1:N])/2.]; 
    
     p13  = - [p12[jump_index2] - jump2 ; px13[jump_index2:N] ];
     p23  = - [p22[jump_index2]         ; px23[jump_index2:N-1] ; px2f ];
    
     p1     = [p11 ; p12 ; p13 ]
     p2     = [p21 ; p22 ; p23 ]

**Comment by ocots** [comment]
Cela m'étonnes que tu aies besoin d'ajouter un saut dans la méthode directe. Mais sinon, écris le message d'erreur dans la discussion.

**Comment by AnasXbouali** [comment]
En effet, si tu regardes le problème avec une région "zermelo_control_loss", j'ai intégré le saut dans la méthode indirecte (l'énoncé du PMP avec perte de contrôle) et la méthode reste convergente. De plus, dans le vecteur adjoint, $p_2$ admet deux sauts (en $t_1$ et $t_2$ les deux temps de croisement), contrairement au vecteur adjoint donné par la méthode indirecte. Est-ce que cela n'est pas problématique ?

**Comment by ocots** [comment]
Je te propose de faire un point visio sur Discord pour en discuter. Cet aprem 15h ?

**Comment by ocots** [comment]
On garde ce que l'on a dit cet aprem mais je me dis finalement que l'idée d'ajouter un contrôle $v$ pour contrôler la dynamique du contrôle constant sur les régions de perte de contrôle, ça pourrait être une bonne idée. Si je note $\lambda$ le paramètre vu comme une variable d'état. On met $\dot{\lambda} = 0$ sur les régions de perte de contrôle et $\dot{\lambda} = v$ sur les régions du contrôle permanent. Ensuite, il faut ajouter un critère de type $L^2$ pour avoir unicité de la solution, on ajoute donc 
```math
\int v^2(t) dt
```
dans le critère. Cependant, cela va modifier la solution optimale. Du coup, on peut ajouter un petit paramètre $\varepsilon$ en facteur de la norme $L^2$ de $v$ :
```math 
\varepsilon \int v^2(t) dt.
```
Je pense que pour un $\varepsilon$ assez petit, en plus de l'unicité, on retrouve la solution du problème de départ. Ca doit se montrer sous certaines hypothèses.

Est-ce que tu peux essayer cette idée, je pense que ce n'est pas très lourd à mettre en place ?

**Comment by AnasXbouali** [comment]
Tout à fait, on peut ajouter le cout $\mathrm{L}^2$ avec $\epsilon>0$ suffisamment petit. Je trouve que c'est une bonne idée! 
Du coup, je vais essayer de la mettre en place et je te tiens au courant une fois faite.

En ce qui concerne la technique d'augmentation pour le problème de Zermelo avec une seule perte de controle, j'ai réussi à trouvé la meme solution (état et controle). Au niveau de la récupération des vecteurs adjoint on remarque maintenant un saut (mais juste ponctuel en $t_1$ et $t_2$).
Je précise que j'ai ajouter des contraints d'états : 

`con_y1[j=1:N+1],  y1[j] <= 0.5 `
 
` con_y2[j=1:N+1], 0.5 <= y2[j] <= 3.5 `
       
` con_y3[j=1:N+1], 3.5 <= y3[j] `

notebook : https://github.com/control-toolbox/control-loss/blob/main/zermelo_control_loss_aug.ipynb

**Comment by ocots** [comment]
J'ai voulu essayé la norme L2 sur v mais après avoir tout mis en place, j'obtiens une solution meilleure que celle que tu avais et il n'y a qu'un passage dans la zone de perte de contrôle : https://github.com/control-toolbox/control-loss/blob/L2v/ho_permanent-loss.ipynb

Après, si la solution du problème permanent est un contrôle constant par morceaux, est-ce que l'on va voir grand chose dans le cas perte de contrôle...

**Comment by ocots** [comment]
j'ai fait du min énergie ici : https://github.com/control-toolbox/control-loss/blob/L2v/ho_permanent-loss-energy.ipynb

On a bien deux passages et cela me semble propre.

**Comment by AnasXbouali** [comment]
Tout à fait, "https://github.com/control-toolbox/control-loss/blob/L2v/ho_permanent-loss.ipynb" trouve la solution optimale (que j'ai trouvée à la main). Je pense que l'idée de considérer un contrôle $v$ permet de prendre en compte un paramètre régional (je vais essayer de l'appliquer également à l'exemple de Zermelo avec deux régions de perte de contrôle).

Dans le cas de perte de contrôle (pour l'oscillateur harmonique), on aura des valeurs de $\lambda \in (-1,1)$, mais pas pour toutes les conditions initiales. Par exemple, si on prend la condition initiale (4.2, 0), on aura une commande {+1, -1, 0.73}. Plus précisément, lorsqu'on atteint [(0,0), (2,0)], on prend une commande constante (modérée).

**Comment by ocots** [comment]
Et tu as vu ça ? En bleu le contrôle constant $\lambda$ et en rouge le contrôle permanent $u$. Les zones grises sont les moment où l'on se trouve dans une zone de perte de contrôle.

![Capture d’écran 2023-03-18 à 18 11 15](https://user-images.githubusercontent.com/66357348/226122270-8033eae1-c8ec-4c80-bdc5-e0ccd50553cc.png)

**Comment by AnasXbouali** [comment]
Ah oui, je viens de consulter le fichier ; En effet, dans ce cas, il est très intéressant d'avoir un contrôle $u(t)$ non-constant dans la zone de contrôle, ainsi que des valeurs modérées du paramètre régional qui changent à chaque visite.

**Comment by ocots** [comment]
Voici le critère
```julia
@objective(sys, Min, ε*xv[N+1]+xu[N+1])
```

La partie `xu[N+1]` c'est la norme L2 du contrôle $u$, cf. `@NLexpression(sys, dxu[j = 1:N+1], u[j]^2 )`.

La partie `ε*xv[N+1]` c'est celle qui permet d'avoir un contrôle $v$ unique.

Et pour le paramètre régional, on a
```julia
@NLexpression(sys,  dλ[j = 1:N+1], ifelse(x2[j] > 0. , v[j], 0. ) )
```
comme ça il peut évoluer dans les zones classiques.

**Comment by ocots** [comment]
Tu remarqueras que pour le problème temps min, j'ai un critère de la forme
```julia
@objective(sys, Min, T+ε*xv[N+1]+xu[N+1])
```
où il y a aussi une partie `xu[N+1]`. Mais c'est pour mettre le contrôle $u$ à 0 dans les régions de perte de contrôle, cf.
```julia
@NLexpression(sys, dxu[j = 1:N+1], ifelse(x2[j] > 0. , 0., u[j]^2 ))
```
Sinon, quelque part c'est mal défini, il y a une infinité de solution pour le contrôle $u$ sur les régions de perte de contrôle.

**Comment by ocots** [comment]
Après, ce serait bien de remplacer les `ifelse` par des régularisations pour avoir aussi les sauts sur l'adjoint.

**Comment by AnasXbouali** [comment]
En fait, dans le problème de temps minimum, on peut enlever la norme 2 du contrôle $u$ (i.e. son état augmenté $xu$). Je viens de tester, et ça donne un contrôle nul dans les zones de non-contrôle. Dans ces zones, la dynamique $u(t) - x(t)$ n'est pas active, donc il prend automatiquement $u(t) = 0$.

**Comment by ocots** [comment]
C'est l'algo qui fait ça mais en soi c'est mal posé. Quelque part, c'est mieux de laisser car le problème est alors bien posé et on sait ce qu'il va se passer. Je pense qu'il met 0 car c'est au milieu des bornes.

**Comment by AnasXbouali** [comment]
Ah oui, c'est vrai que le problème avec $(\lambda, u)$ est mal posé. Cependant, le problème initial n'a qu'un contrôle $u^{\star}$ qui doit être constant dans les zones de non-contrôle. Par conséquent, il s'agit de concaténer $(\lambda, u)$, ce qui signifie que même si $u=0$ dans les zones de non-contrôle, on obtiendra toujours $u^{\star}= \lambda$.

Je vais modifier le `ifelse` en utilisant la technique de régularisation, tout en conservant la même approche avec la norme 2 de $v$ avec $\epsilon > 0$.

**Comment by ocots** [comment]
Ce qui est mal posé bien sûr, ce n'est pas le problème de contrôle optimal mais seulement le problème d'optimisation comme il est posé pour être résolu par `JuMP`.

**Comment by AnasXbouali** [comment]
J'ai mis à jour le fichier : 
https://github.com/control-toolbox/control-loss/blob/main/ho_permanent-loss.ipynb 

en y incluant la régularisation. Ainsi, pour la méthode directe, j'obtiens de bons résultats. Cependant, la méthode indirecte ne converge pas.

Voici comment j'ai construit la méthode :

Pour le premier morceau de la trajectoire, étant donné que dans la méthode directe on a $\lambda_1 =1$, je ne définis pas $\lambda_1$ comme paramètre (la condition du gradient moyen ne vaut pas zéro).

Pour le deuxième morceau, remarquons que je n'ai pas mis de saut sur le vecteur $p_2$ car j'ai la formule suivante :

$$ p_2^+(t^c_1) - p_2^-(t^c_1) = - \frac{p_{2}^{-}(t^{c}_{1})(u^{+}(t^{c}_{1}) - \lambda_1) }{u^{+}(t^{c}_{1}) - x{1}(t^{c}_{1})}$$

où $t^c_1$ est le premier temps de croisement et on a $u^{+}(t^{c}_{1}) - \lambda_1 = 0$.

Pour le dernier segment de trajectoire, j'ai ajouté un saut `jump2` qui vérifie la relation suivante :

$$ p_2^+(t_2^c) - p_2^-(t_2^c) = -\frac{p_2^-(t_2^c)(\lambda_2 - u^-(t_2^c))}{\lambda_2 - x_1(t_2^c)} $$

où $t_2^c$ est le premier instant de croisement.

**Comment by ocots** [comment]
Je pense que l'on peut fermer cette issue.
