### ISSUE TITLE
Nettoyage branche `control-loss` sur gitlab

### ISSUE THREAD

**Issue by ocots** [control-toolbox/control-loss#3]
@AnasXbouali Serait-il possible de nettoyer la branche [control-loss](https://gitlab.inria.fr/ct/gallery/-/tree/control-loss/examples/control-loss) sur gitlab ? L'idée est de supprimer tous les notebooks à l'exception de celui visible sur la galerie : 
```
double-integrator-with-control-loss-and-no-control.ipynb
```

Tu peux déplacer tous les notebooks (nettoyés si besoin) dans ce repo et ensuite supprimer les notebooks inutiles sur gitlab puis je pourrai supprimer la branche `control-loss` sur gitlab et nettoyer la branche `master` sur gitlab.

* [x] @AnasXbouali déplacer les notebooks de gitlab à github
* [x] @AnasXbouali supprimer de la branche `control-loss` de gitlab les notebooks à l'exception de un seul
* [x] @ocots supprimer la branche `control-loss` de gitlab
* [x] @ocots nettoyer la branche `develop` de gitlab

**Comment by AnasXbouali** [comment]
@ocots ; sur Gitlab je ne peux pas supprimer aucun fichier du dossier `control loss`. 

![Screenshot from 2023-03-25 15-06-22](https://user-images.githubusercontent.com/17778368/227751249-7698bfdc-e9b8-4167-94b4-d675381d5659.png)

![Screenshot from 2023-03-25 15-06-46](https://user-images.githubusercontent.com/17778368/227751245-d2614d97-1a51-4670-8c43-45bc0244ce9b.png)

**Comment by ocots** [comment]
Attention, tu ne dois pas le faire dans la branche `master` mais dans la branche `control-loss` !

https://gitlab.inria.fr/ct/gallery/-/tree/control-loss/examples/control-loss

**Comment by AnasXbouali** [comment]
Ok, je viens de supprimer tous les notebooks que j'ai déplacés sur Github de la branche `control-loss.` Je n'ai laissé qu'un seul fichier (flow.jl).

![Screenshot from 2023-03-26 17-20-04](https://user-images.githubusercontent.com/17778368/227785684-027677a7-bb74-41d7-a946-1ddfcceccd4b.png)

**Comment by ocots** [comment]
Il aurait fallu laisser `double-integrator-with-control-loss-and-no-control.ipynb` s'il était plus à jour que sur la branche `master`.

**Comment by AnasXbouali** [comment]
C'est fait. J'ai mis `double-integrator-with-control-loss-and-no-control.ipynb` dans la branche `control loss`. Notons que j'ai retravaillé le double intgerateur avec perte de controle (en utilisant l'augmentation avec les états `xu` et `xv`) dans le notebook suivant : 

https://github.com/control-toolbox/control-loss/blob/main/double%20integrator/loss.ipynb
