### ISSUE TITLE
[Bug] New version of OptimalControl

### ISSUE THREAD

**Issue by ocots** [control-toolbox/control-loss#31]
@AnasXbouali The new version of OptimalControl has no field `times` anymore for an `OptimalControlSolution`.

There is a bug in the documentation of the application due to that: https://github.com/control-toolbox/control-loss/actions/runs/10654653971/job/29531246291#step:6:27

**Comment by AnasXbouali** [comment]
I noticed that the command 
```julia
tt = sol.times
```
is no longer working, so I am replacing it with
```julia 
tf     = sol.variable
tt = (0:N+1) * value.(tf/(N+1))
```
